### ISSUE TITLE
Does slurm-pipeline has CPUs per task option?

### ISSUE THREAD

**Issue by avatar-lavventura** [acorg/slurm-pipeline#42]
`sbatch` has a option `-c`, which is: `-c, --cpus-per-task=ncpus   number of cpus required per task`. 

**[Q]** What should I do to provide `-c` (coreNumber) that will used by each script on the pipeline under `slurm-pipeline.py` ? 

As I understand `slum-pipeline.py` does not use SLURM at all. But I can submit `slurm-pipeline.py` workflow using `sbatch` by proving core number that I want to use.

**Comment by terrycojones** [comment]
Hi. Yes, as you say, the slurm-pipeline code does not call sbatch. One way to provide such a thing would be to pass it with, e.g., `--scriptArgs '-c 4'`. That will result in two things: 1) Scripts that have no dependencies will get those arguments on the command line, and 2) the environment variable `SP_ORIGINAL_ARGS` will be set to contain `-c 4` and be accessible to all scripts. So that's one way to pass information to all scripts. Other options would be to just use a regular environment variable yourself, though of course you would have to make sure it was set at run time when SLURM actually ran your scripts (not just when you invoke `sbatch`), or to put the value in a config file that all scripts read (I often do things that way, which is easy when all scripts are written in the same language).

Does that help?

It would be possible to add a command line option to `slurm-pipeline.py` to allow the explicit passing of environment variables. These would then be available to the scripts that `slurm-pipeline.py` invokes. If those scripts wanted to pass on environment variables to the scripts that `sbatch` would be given, the values can be passed using the `--export` option to `sbatch`.  Does that makes sense?  In summary, the flow would be: User calls e.g., `slurm-pipeline.py --env VAR1=VALUE1 --env VAR2=VALUE2 ...` and `slurm-pipeline.py` adds those variables to the environment it creates for all the scripts in the specification. Those scripts in turn pass the values (and all others, if wanted) on to scripts later run by `sbatch` by calling `sbatch --export=VAR1,VAR2,ALL`.

**Comment by terrycojones** [comment]
I was thinking about this a bit more and I think you can just use the environment with no changes needed. `slurm-pipeline.py` passes on its env to the script you specify. So you should be able to do something like

```sh
$ env SBATCH_ARGS='-c 4' slurm-pipeline.py ...
```

and then in your scripts just use `sbatch $SBATCH_ARGS ...`.

**Comment by avatar-lavventura** [comment]
Thank you for the detail answer. I want to integrate `slurm-pipeline.py` with `sbatch` and it more clear on my mind using `slurm-pipeline` but I am still little bit lost.

I need to add a wrapper script for each script I need to use such as for `long-words-only.sh`.

**long-words-only_run.sh**:

```
#!/bin/bash
#SBATCH -o slurm.out        # STDOUT
#SBATCH -e slurm.err        # STDERR
#SBATCH --mail-type=ALL

bash long-words-only.sh
```

And this will be called via in `specification.json` as `"script": "scripts/one-word-per-line_sbatch.sh"`

**long-words-only_sbatch.sh**:
```
#!/bin/bash
sbatch -c4 long-words-only_run.sh
```

But I am not sure how would `slurm-pipeline.py` detect to continue task on the pipeline when scripts that are running under `sbatch` is completed.

**Comment by terrycojones** [comment]
OK, good question.  You need to output the SLURM job ids of any jobs you start with `sbatch`. So, something like

```sh
jobid=$(sbatch $SP_DEPENDENCY_ARG $SP_NICE_ARG long-words-only_run.sh | cut -f4 -d' ')
echo TASK: task-name $jobid
```

This is described in the README, but it may not be clear enough.  The `task-name` part is any name you want to assign to the task you just submitted an `sbatch` job for. The task name will be passed along to any subsequent dependencies.  `slurm-pipeline.py` reads this output and collects all the SLURM job ids that are output by dependencies and puts something into `SP_DEPENDENCY_ARG` so that you can pass the correct dependency info to your next script (if there is one) when you next use `sbatch`.  Make sense?

**Comment by avatar-lavventura** [comment]
I am not an expert but it may be risky to use `SP_DEPENDENCY_ARG` as environment name since if multiple `slurm-pipeline` process is running at the same time they may overwrite each others' environment variable. Maybe if a counter kept for each submitted `slurm-pipeline`, something like `SP_DEPENDENCY_ARG_X`. `X` will incremented.

------------

Thanks. I was able to make it work and I got the idea. Please see the changes made on the script (https://github.com/avatar-lavventura/slurm-pipeline/tree/master/examples/word-count/scripts). I did not add `sbatch` option for the `summarize.sh` script.

Sorry for too many questions. I did not understand that how tasks on the pipeline receives the arguments that we want them to receive. 

For example `long-words-only.sh` obtain its arguments one by one as but how:

```
1-karamazov
2-trial
3-ulysses
```

And can it also get the output of its dependent job's output that is written into a file something like:

`1-karamazov output.txt'

**Comment by terrycojones** [comment]
There's no risk of the environment variables clashing because each process has its own environment - it is not a global thing.

**Comment by avatar-lavventura** [comment]
Got it, sorry I though it was setting `bash`'s environment variable.

**Comment by terrycojones** [comment]
No problem. In general it is impossible for a program that you run from the shell to set the environment of that shell, at least if the program is written in C, Python, etc.   A shell script can do it, but only if it is run in the current shell (not in a freshly created shell, as happens when you put `#!/bin/bash` at the start of a file, make that file executable, and run it from the command line).  The `source` (or `.`) command will read commands from a script and execute them in the current shell. That, and shell functions, is the only way to change the environment in the current shell, unless you do it manually in the shell on the command line.

On the other hand, a program written in C, Python, etc., can prepare a fresh environment for a new process it is about to create.  That's what `slurm-pipeline.py` does.
