### ISSUE TITLE
How we decide which arguments are passed between tasks?

### ISSUE THREAD

**Issue by avatar-lavventura** [acorg/slurm-pipeline#43]
**[Q]** How tasks or dependent jobs on the pipeline receives arguments that we want them to receive? 

For example, on the `word-count` example, `long-words-only.sh` obtains its arguments one by one as follow:

```
1-karamazov
2-trial
3-ulysses
```

But one the other hand, `one-word-per-line.sh` receives its arguments as follows:

`texts/1-karamazov.txt texts/2-trial.txt texts/3-ulysses.txt`

=> How or at which part of the code those arguments are decided? 

And also can a task obtain the output of its dependent job's output (`output.txt`) that is written into a file as an argument something like: 

`1-karamazov output.txt` or only `output.txt` instead of receiving its dependent job's argument.

**Comment by terrycojones** [comment]
`one-per-line.sh` is the first script and so has no dependencies (see `specification.json`). Scripts that have no dependencies are called with all the values from `--scriptArgs`.  That script echoes 3 task names (`1-karamazov`, `2-trial`, and `3-ulysses`). So `long-words-only.sh` is in fact called 3 times. It is passed the task name from the step it is dependent on.

If a step script needs to operate on the output of a previous step, it has to know where to find that output. `slurm-pipeline.py` has zero knowledge of what your scripts do or where/when they are run, etc.  That's all run-time information that happens (probably) long after `slurm-pipeline.py` has exited. So whether your script puts output in a file, or into a database, or something else, the next script in your pipeline is expected to know where to find that output.

You have to keep in mind the difference between what happens at the time of scheduling the scripts to be run (which is what `slurm-pipeline.py` helps with, in particular with dependencies) and what happens some time later (due to SLURM) when whatever scripts you gave to `sbatch` in the submission phase actually run. `slurm-pipeline.py` has absolutely nothing to do with that latter phase.

**Comment by avatar-lavventura** [comment]
In `one-per-line.sh` tasks are echoed as called as follows:

```
TASK: 1-karamazov 86
TASK: 2-trial 87
TASK: 3-ulysses 88
```

But how `texts/1-karamazov.txt`, `texts/2-trial.txt`, `texts/3-ulysses.txt`, respectively is sent as an argument to `long-words-only.sh`. 

=> Could I provide more than one argument, for example:

`texts/1-karamazov.txt input_1.txt input_2.txt` into  `long-words-only.sh`?

**Comment by terrycojones** [comment]
Yes, you could. The reason `long-words-only.sh` is called 3 times is because it is not a `collect` step. So it is assumed you want to run it once separately (presumably each one launches an `sbatch` script to be run in parallel on different nodes) for each file.  That makes sense in this case because all that work can be done in parallel. The next step, `summarize`, needs all the previous tasks to be complete before it can run, so it has `"collect": true` in the specification and it gets all 3 task names on the command line.

If you put `"collect": true` in the specification for `long-words-only.sh` it will only be called once, and it will get the three tasks names as options.

**Comment by avatar-lavventura** [comment]
I got it, since `long-words-only.sh` is not a `collect` step, it is called separately for each given argument in its order, right?

Maybe I can do something like:
`--scriptArgs texts/1-karamazov.txt,output_1.txt texts/2-trial.txt,output_2.txt texts/3-ulysses.txt,output_3.txt`

and split provided input with `,` this will leads me to provide multiple arguments.

**Comment by terrycojones** [comment]
Yes to the first question.

And you could do what you suggest if you wanted to. The task names are completely up to you. If you did it that way, I guess it would mean that you are figuring something out in `one-per-line.sh` that is not known in advance (because otherwise you could just put the same information into `long-words-only.sh` and not need to pass it along in the task name).
